# Generated by Django 3.0.8 on 2020-08-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Не указан')], default='other', max_length=6, verbose_name='sex'),
        ),
    ]
