# Generated by Django 4.0.1 on 2022-02-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/placeholder_200x200.png', null=True, upload_to='images'),
        ),
    ]
