# Generated by Django 3.1 on 2020-09-04 21:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
